---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Workflow_AWS SecretsManager create secret.yaml
  - Workflow_AWS SecretsManager delete secret.yaml
  - Workflow_Azure KeyVault create secret.yaml
  - Workflow_Azure KeyVault delete secret.yaml
  - Workflow_AWS SecretsManager update secret.yaml
  - Workflow_Azure KeyVault update secret.yaml
