---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Workflows/Secret Management
  home: Digital.ai - Official/Workflows/Secret Management
spec:
- template: Azure KeyVault update secret
  description: "Easily update secrets in Azure KeyVault, which can be looked up and\
    \ substituted across Digital.ai Release templates and workflows."
  scheduledStartDate: 2023-09-12T09:00:00+05:30
  dueDate: 2023-09-12T10:00:00+05:30
  phases:
  - phase: Update Secret
    tasks:
    - name: Create|Select Azure KeyVault Connection
      type: xlrelease.UserInputTask
      description: Select or create a new Azure KeyVault connection.
      variables:
      - azure_key_vault
    - name: Specify Secret Details
      type: xlrelease.UserInputTask
      description: Enter the secret name and value. Secret value should be plain text.
      variables:
      - vault_name
      - secret_name
      - secret_value
    - name: Update Secret
      type: azureKeyvault.SetSecret
      vaultName: "${vault_name}"
      secretName: "${secret_name}"
      description: Updates a secret with the specified value.
      variableMapping:
        pythonScript.keyvaultServer: "${azure_key_vault}"
        pythonScript.secretValue: "${secret_value}"
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Cloud & Container
  variables:
  - type: xlrelease.StringVariable
    key: secret_name
    showOnReleaseStart: false
    label: Secret Name
    description: Name of the secret
  - type: xlrelease.PasswordStringVariable
    key: secret_value
    showOnReleaseStart: false
    label: Secret Value
    description: Value of the secret as plain text
  - type: xlrelease.ReferenceVariable
    key: azure_key_vault
    showOnReleaseStart: false
    label: Azure KeyVault Server
    description: Connection to Azure KeyVault
    referencedType: azure.KeyvaultServer
  - type: xlrelease.StringVariable
    key: vault_name
    showOnReleaseStart: false
    label: Vault Name
    description: Azure KeyVault Name
  disableNotifications: true
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/svg+xml
    file: !file "template-logo/d98558d36ffc1d7f04dfd258d462841190d8d34b/azure.svg"
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
