# Exported from:        http://DESKTOP-9S08TE1:5516/
# Release version:      24.1.2
# Date created:         Thu Jan 09 18:03:18 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_Setup Release Folders and Variables.yaml
