---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Workflows/Digital.ai Deploy
  home: Digital.ai - Official/Workflows/Digital.ai Deploy
spec:
- template: Azure setup application with Digital.ai Deploy
  description: "Seamlessly create an application in Digital.ai Deploy that can create\
    \ Azure resource groups, including its respective environment and infrastructure\
    \ setup."
  scheduledStartDate: 2023-03-23T09:00:00+05:30
  dueDate: 2023-03-23T10:00:00+05:30
  phases:
  - phase: Setup Infra and Env
    tasks:
    - name: Specify Deploy Server Details
      type: xlrelease.UserInputTask
      description: Select the Digital.ai Deploy Server Connection onto which the Azure
        application has to be created. You can create a new connection if you have
        not created one.
      variables:
      - deployServer
    - name: Specify Environment Name
      type: xlrelease.UserInputTask
      description: Specify the name of the environment CI to be created in the Digital.ai
        Deploy Server.
      variables:
      - environmentName
    - name: Create Environment
      type: deploy.CreateCI
      description: Creates an environment CI with the given name in the Digital.ai
        Deploy Server.
      variableMapping:
        server: "${deployServer}"
      capabilities:
      - remote
      ciID: "Environments/${environmentName}"
      ciType: udm.Environment
      jsonDescriptor: "{}"
    - name: Specify Azure Connection Parameters
      type: xlrelease.UserInputTask
      description: Specify the Azure connection details. The Azure Cloud CI in the
        Digital.ai Deploy Server will be created with the specified details.
      variables:
      - azurecloud-identifier
      - subscriptionId
      - tenantId
      - clientId
      - clientSecret
    - name: Configure Azure Connection
      type: deploy.CreateCI
      description: Creates an Azure Cloud CI in the Digital.ai Deploy Server with
        the details specified in the previous step.
      variableMapping:
        server: "${deployServer}"
      capabilities:
      - remote
      ciID: "Infrastructure/${azurecloud-identifier}"
      ciType: azure.Cloud
      jsonDescriptor: |-
        {
            "authMethod":"directory-application-and-service-principal",
            "subscriptionId":"${subscriptionId}",
            "tenantId":"${tenantId}",
            "clientId":"${clientId}"
        }
      addToEnvironment: true
      envID: "Environments/${environmentName}"
    - name: Set Azure Credentials
      type: deploy.UpdateCIPropertyWithSecretValue
      description: Sets the secret information in the previously created Azure Cloud
        CI in Digital.ai Deploy server.
      variableMapping:
        propertyValue: "${clientSecret}"
        server: "${deployServer}"
      capabilities:
      - remote
      ciID: "Infrastructure/${azurecloud-identifier}"
      ciProperty: clientKey
    - name: Check Azure Connection
      type: deploy.ControlTask
      description: Runs a Check Connection control task on the created Azure Cloud
        CI in the Digital.ai Deploy server to validate the specified credentials.
      variableMapping:
        server: "${deployServer}"
      capabilities:
      - remote
      ciId: "Infrastructure/${azurecloud-identifier}"
      taskName: checkConnection
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#3d6c9e'
  - phase: Setup Application
    tasks:
    - name: Specify Application Name
      type: xlrelease.UserInputTask
      description: Specify the name of the application to be created in the Digital.ai
        Deploy server.
      variables:
      - applicationName
    - name: Create Application
      type: deploy.CreateCI
      description: Creates an application with the specified name in the Digital.ai
        Deploy server.
      variableMapping:
        server: "${deployServer}"
      capabilities:
      - remote
      ciID: "Applications/${applicationName}"
      ciType: udm.Application
      jsonDescriptor: "{}"
    - name: Specify Package Name
      type: xlrelease.UserInputTask
      description: Specify a package name to be created within the application created
        in Digital.ai Deploy server in the previous step.
      variables:
      - packageName
    - name: Create Deployment Package
      type: deploy.CreateCI
      description: Creates a deployment package with the specfied name in the application
        created in Digital.ai Deploy server.
      variableMapping:
        server: "${deployServer}"
      capabilities:
      - remote
      ciID: "Applications/${applicationName}/${packageName}"
      ciType: udm.DeploymentPackage
      jsonDescriptor: "{}"
    - name: Specify Resource Group Parameters
      type: xlrelease.UserInputTask
      description: Specify the resource group information which will be used to create
        the application package in Digital.ai Deploy server.
      variables:
      - resourcegroupName
      - resourcegroupLocation
    - name: Create Sample Resource Group
      type: deploy.CreateCI
      description: Creates the Azure Resource Group CI in the Digital.ai Deploy server
        with the details specified in the previous step.
      variableMapping:
        server: "${deployServer}"
      capabilities:
      - remote
      ciID: "Applications/${applicationName}/${packageName}/sample-resource-group"
      ciType: azure.ResourceGroupSpec
      jsonDescriptor: |-
        {
            "location":"${resourcegroupLocation}",
            "resourceGroupName":"${resourcegroupName}"
        }
    - name: Add managed application
      type: managedApplications.CreateApplication
      applicationName: "${applicationName}"
      managedBy: Digital.ai Deploy
      environmentTag: "${environmentName}"
      applicationReference: "${applicationName}"
      description: Adds the created Azure Resource Group application to the Digital.ai
        Release managed application list.
      variableMapping:
        pythonScript.connectionServer: "${deployServer}"
        pythonScript.managedApplicationId: "${managedApplicationId}"
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Application onboarding
  variables:
  - type: xlrelease.StringVariable
    key: environmentName
    description: Name of the environment CI in Deploy
    value: azure-env
  - type: xlrelease.StringVariable
    key: applicationName
    description: Name of the application CI in Deploy
    value: azure-app
  - type: xlrelease.StringVariable
    key: packageName
    description: Name of the application package in Deploy
    value: "1.0"
  - type: xlrelease.StringVariable
    key: azurecloud-identifier
    description: Name of the Azure Cloud CI
    value: azure-cloud
  - type: xlrelease.StringVariable
    key: clientId
    description: Azure Client Id
    value: client-id
  - type: xlrelease.PasswordStringVariable
    key: clientSecret
    showOnReleaseStart: false
    description: Azure Client Secret
  - type: xlrelease.StringVariable
    key: subscriptionId
    showOnReleaseStart: false
    description: Azure Subscription Id
    value: subscription-id
  - type: xlrelease.StringVariable
    key: tenantId
    description: Azure Tenant Id
    value: tenant-id
  - type: xlrelease.StringVariable
    key: resourcegroupLocation
    description: Location of the Resource Group in Azure
    value: East US
  - type: xlrelease.StringVariable
    key: resourcegroupName
    description: Name of the Resource Group in Azure
    value: resourcegroup-name
  - type: xlrelease.ReferenceVariable
    key: deployServer
    showOnReleaseStart: false
    label: Deploy Server
    description: Connection to the Deploy Server
    referencedType: digitalai.DeployServer
  - type: xlrelease.StringVariable
    key: managedApplicationId
    requiresValue: false
    showOnReleaseStart: false
    label: Application ID
    description: Application ID in Digital.ai Release
  disableNotifications: true
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/svg+xml
    file: !file "template-logo/97662a62108c2b1e1875c8e18f6d1c72a013d33c/deploy.svg"
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
