---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Workflow_Digital.ai Release runner additional install in Kubernetes.yaml
  - Workflow_Digital.ai Release runner install in Kubernetes.yaml
  - Workflow_Digital.ai Release runner install with Digital.ai Cloud Connector.yaml
