# Exported from:        http://DESKTOP-9S08TE1:5516/
# Release version:      24.1.2
# Date created:         Thu Jan 09 17:49:47 IST 2025

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: sam_222011
spec:
- directory: "."
  teams:
  - name: Release Admin
    users:
    - admin
    permissions:
    - app_pipelines#view
    - folder#view
    - release#abort
    - release#advance_task_transition
    - release#edit
    - release#edit_blackout
    - release#edit_failure_handler
    - release#edit_precondition
    - release#edit_security
    - release#edit_task
    - release#edit_task_attachments
    - release#edit_task_configuration_facet
    - release#edit_task_dates
    - release#edit_task_description
    - release#edit_task_flag
    - release#edit_task_input_output_properties
    - release#edit_task_script
    - release#edit_task_tags
    - release#lock_task
    - release#reassign_task
    - release#restart_phase
    - release#start
    - release#task_transition
    - release#view
    - trigger#edit_trigger
    - trigger#view_trigger
    - workflow#abort_execution
    - workflow#start_execution
    - workflow#view_execution
  - name: Folder Owner
    users:
    - admin
    permissions:
    - app_pipelines#edit
    - app_pipelines#view
    - dashboard#edit
    - dashboard#view
    - delivery#edit
    - delivery#edit_tracked_item
    - delivery#view
    - delivery_pattern#edit
    - delivery_pattern#view
    - folder#apply_changes
    - folder#edit
    - folder#edit_configuration
    - folder#edit_notifications
    - folder#edit_security
    - folder#edit_variables
    - folder#edit_versions
    - folder#generate_configuration
    - folder#view
    - folder#view_versions
    - group#edit
    - group#view
  - name: Template Owner
    users:
    - admin
    permissions:
    - app_pipelines#view
    - folder#view
    - template#create_release
    - template#create_release_other_folder
    - template#edit
    - template#edit_failure_handler
    - template#edit_precondition
    - template#edit_security
    - template#edit_triggers
    - template#lock_task
    - template#view
    - trigger#view_trigger
